name: Build and Push Docker Image

on:
  push:
    tags: ['v*']

env:
  DOCKER_HOST: tcp://localhost:2375

jobs:
  build:
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login git.nebulahvelvet.no -u stianmjo --password-stdin

      - name: Build and push
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          IMAGE=git.nebulahvelvet.no/stianmjo/gjallar
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
