# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  mirror:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.nebulahvelvet.no/stianmjo/gjallar.git
          git push gitlab --all --force
          git push gitlab --tags --force
